PORT=5000

# AUTH DB (Postgres - YOU)
AUTH_DB_HOST=10.11.244.236
AUTH_DB_USER=DANISH #change to your username 
AUTH_DB_PASSWORD="1234" 
AUTH_DB_NAME=hopeplates
AUTH_DB_PORT=5432

# DONATION DB (Aina-MariaDB - FRIEND)
DONATION_DB_HOST=10.11.244.179
DONATION_DB_USER=DANISH
DONATION_DB_PASSWORD="1234"
DONATION_DB_NAME=hopeplates
DONATION_DB_PORT=3306

# =====================
# INVENTORY DB (FRIEND)
# =====================
INVENTORY_DB_HOST=10.11.244.174
INVENTORY_DB_USER=DANISH
INVENTORY_DB_PASSWORD="1234"
INVENTORY_DB_NAME=hopeplates
INVENTORY_DB_PORT=3306
# =====================

# =====================
# FOOD DISTRIBUTION DB
# =====================
FOOD_DB_HOST=10.11.244.55
FOOD_DB_USER=DANISH
FOOD_DB_PASSWORD="1234"
FOOD_DB_NAME=hopeplates
FOOD_DB_PORT=3306

# =====================
# BENEFICIARY / APPLICATION DB (POSTGRES)
# =====================
BENEFICIARY_DB_HOST=10.11.244.106
BENEFICIARY_DB_USER=postgres
BENEFICIARY_DB_PASSWORD=1234
BENEFICIARY_DB_NAME=hopeplates
BENEFICIARY_DB_PORT=5432