// dataExample/DonationExp.js

export const donationStock = [
  {
    id: 1,
    item: "Rice (5kg)",
    category: "Dry Food",
    quantity: 50,
    unit: "packs",
    expiry: "2025-06-12",
    donor: "Mr. Lim",
    status: "OK",
  },
  {
    id: 2,
    item: "Fresh Milk",
    category: "Perishable",
    quantity: 12,
    unit: "cartons",
    expiry: "2025-01-04",
    donor: "Aeon Mall",
    status: "EXPIRING",
  },
  {
    id: 3,
    item: "Canned Sardines",
    category: "Canned Food",
    quantity: 80,
    unit: "cans",
    expiry: "2026-03-12",
    donor: "Tesco",
    status: "OK",
  },
  {
    id: 4,
    item: "Instant Noodles",
    category: "Dry Food",
    quantity: 120,
    unit: "packs",
    expiry: "2025-07-20",
    donor: "Food Bank Malaysia",
    status: "OK",
  },
  {
    id: 5,
    item: "Cooking Oil (1L)",
    category: "Dry Food",
    quantity: 34,
    unit: "bottles",
    expiry: "2025-05-10",
    donor: "Mr. Wong",
    status: "OK",
  },
  {
    id: 6,
    item: "Mineral Water",
    category: "Beverages",
    quantity: 60,
    unit: "bottles",
    expiry: "2026-01-01",
    donor: "Nestlé",
    status: "OK",
  },
  {
    id: 7,
    item: "Bread Loaves",
    category: "Perishable",
    quantity: 18,
    unit: "loaves",
    expiry: "2024-12-02",
    donor: "Family Mart",
    status: "EXPIRING",
  },
  {
    id: 8,
    item: "Milk Powder",
    category: "Dry Food",
    quantity: 22,
    unit: "tins",
    expiry: "2025-11-11",
    donor: "Dairy Home",
    status: "OK",
  },
  {
    id: 9,
    item: "Chocolate Drink",
    category: "Beverages",
    quantity: 30,
    unit: "sachets",
    expiry: "2025-08-05",
    donor: "Youth Club Malaysia",
    status: "OK",
  },
  {
    id: 10,
    item: "Canned Chicken Soup",
    category: "Canned Food",
    quantity: 48,
    unit: "cans",
    expiry: "2025-09-21",
    donor: "Lotus’s",
    status: "OK",
  },
];

// =================== Dashboard Stats ===================
export const donationStats = {
  totalItemsInStock: donationStock.reduce(
    (sum, item) => sum + item.quantity,
    0
  ),
  lowStockAlerts: donationStock.filter((item) => item.quantity <= 20).length,
  monthlyDonations: donationStock.length, // or compute differently if you have date info
};
